# the organization and project key on SonarCloud (.github/workflows/sonar.yml)
sonar.organization=arielkonopka
sonar.projectKey=arielkonopka_Gardens-of-Eris
sonar.coverageReportPaths=./CoverageReports/coverageReport.XML
sonar.sources=src,include,main.cpp
sonar.cfamily.compile-commands=build/compile_commands.json
sonar.sourceEncoding=UTF-8
# Path to test source directories (comma-separated)
sonar.tests=unitTests
#sonar.cfamily.cpp20=true
# Included test file patterns
sonar.test.inclusions=**/*-test.cpp,**/*-tests.cpp
#sonar.java.jdkHome=/usr/lib/jvm/java-1.17.0-openjdk-amd64/
# This is the name and version displayed in the SonarQube UI.
#sonar.projectName=Gardens-of-Eris
#sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
#@sonar.cfamily.customTargetArch=
#sonar.cfamily.customTargetVendor=
#sonar.cfamily.customTargetSystem=
#sonar.cfamily.customTargetEnv=
