name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
     - name: install dependencies
       run: ./build.sh -gh
     - name: build everything
       run: |
         cd ./build
         cmake -S../ -B./
         cmake
       
